import Head from 'next/head';
import Image from 'next/image';
import Layout from '../components/layouts';
import Hero from '../components/sections/hero'
import About from '../components/sections/about'
import Reach from './../components/sections/reach'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Hero />
        <About />
        <Reach />
      </Layout>
    </div>
  )
}
